<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Legacy89DiskKit.Domain/Legacy89DiskKit.Domain.csproj" />
    <ProjectReference Include="../Legacy89DiskKit.CharacterEncoding.Infrastructure/Legacy89DiskKit.CharacterEncoding.Infrastructure.csproj" />
    <ProjectReference Include="../Legacy89DiskKit.DiskImage.Infrastructure/Legacy89DiskKit.DiskImage.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Legacy89DiskKit.Infrastructure/FileSystem/**/*.cs">
      <Link>FileSystem/%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>
</Project>
