<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Legacy89DiskKit.DiskImage.Domain/Legacy89DiskKit.DiskImage.Domain.csproj" />
    <ProjectReference Include="../Legacy89DiskKit.FileSystem.Domain/Legacy89DiskKit.FileSystem.Domain.csproj" />
  </ItemGroup>
</Project>
