<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Legacy89DiskKit.Domain/Legacy89DiskKit.Domain.csproj" />
    <ProjectReference Include="../Legacy89DiskKit.Infrastructure/Legacy89DiskKit.Infrastructure.csproj" />
    <ProjectReference Include="../Legacy89DiskKit.Drive.Application/Legacy89DiskKit.Drive.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Legacy89DiskKit/Fdc/Application/**/*.cs">
      <Link>Fdc/Application</Link>
    </Compile>
  </ItemGroup>
</Project>